[package]
name = "palang-virtual-machine"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
serde_json = "1.0.127"
tokio = { version = "1.39.3", features = ["full"] }
